# Page settings

baseurl = "http://parkayun.kr/"
languageCode = "en-us"
title = "I am Ayun Park."
theme = "hugo-orbit-theme"
googleAnalytics = "UA-50744429-1"

# Do not build files for websites. Need them? Set to false
disableKinds = ["404", "RSS", "sitemap"]

[params]

# Meta
    description = "I am Ayun Park."
    author = "Ayun Park"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ayun Park"
        tagline = "Keep Calm"
        avatar = "me.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: iam@parkayun.kr"
        title = "iam@parkayun.kr"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//parkayun.kr"
        title = "parkayun.kr"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/parkayun"
        title = "linkedin.com/in/parkayun"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Parkayun"
        title = "github.com/Parkayun"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Business Administration"
        college = "Kookmin University"
        dates = "2018 - Present"

        [[params.education.list]]
        degree = "Information and Communication"
        college = "Sunrin Internet High Shcool"
        dates = "2011 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Korean"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Intermediate"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Data Engineer"
        dates = "2017.11 - Present"
        company = "Nexon Korea, Seoul"
        details = ""

        [[params.jobs.list]]
        position = "Programmer"
        dates = "2016.06 - 2017.03"
        company = "Spoqa, Seoul"
        details = ""

        [[params.jobs.list]]
        position = "Technical Leader"
        dates = "2014.07 - 2016.05"
        company = "Add2Paper, Seoul"
        details = ""

        [[params.jobs.list]]
        position = "CTO"
        dates = "2014.02 - 2014.06"
        company = "Klavis, Seoul"
        details = ""

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2013.03 - 2013.12"
        company = "Rainist, Seoul"
        details = ""

    # Challenges section
    [params.challenges]
        enable = true
        icon = "fa-archive"
        title = "Challenges"
        
        [[params.challenges.list]]
        name = "SECUINSIDE CTF 2012"
        dates = "2012"
        result = "Finalist"
        details = "International Competition"
        
        [[params.challenges.list]]
        name = "HDCON 2012"
        dates = "2012"
        result = "Finalist"
        details = "Domestic Competition"
        
        [[params.challenges.list]]
        name = "ISEC 2011 CTF"
        dates = "2011"
        result = "3rd Place"
        details = "International Competition"

    # More section
    [params.more]
        enable = true
        icon = "fa-rocket"
        title = "And more"
        
        [[params.more.list]]
        name = "Mastering Flask"
        link = "http://naver.com"
        detail = "Technical Review"
        
        [[params.more.list]]
        name = "Web backends development using python"
        link = "http://2015.pycon.hk/schedule/topics/web-backends-development-using-python/"
        detail = "Speaker At PyCON HK 2015"

        [[params.more.list]]
        name = "My repositories"
        link = "https://github.com/Parkayun"
        detail = "Open Sources"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
